# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Running code quality check"
  lane :code_quality do
    swiftlint(
      mode: :lint,
      reporter: "html",
      output_file: "fastlane/test_output/lint/lint.html",
      quiet: true
    )

    slather(
      scheme: "cmeviper",
      proj: "cmeviper.xcodeproj",
      workspace: "cmeviper.xcworkspace",
      output_directory: "fastlane/test_output/slather",
      html: true,
      jenkins: true
    )
  end

  desc "Running unit tests"
  lane :unit_test do
    run_tests(scheme: "cmeviper")
  end

  desc "Running all tests and quality check"
  lane :tests do
    code_quality
    unit_test
  end

  desc "Build (packed) application into IPA file"
  lane :pack do
    gym(
      scheme: "cmeviper",
      include_symbols: true,
      include_bitcode: true,
      export_method: 'development'
    )
  end

  desc "Increase build number and commit new version to git repository"
  lane :increase_build_number do
    increment_build_number
    commit_version_bump
  end

  desc "Deploy prepared application to beta"
  lane :deploy_beta do
    crashlytics(
      api_token: "cf5b7b2a0b85639557661dd3502e1baaa3369e3d",
      build_secret: "c07a081c359ab2299fa2c41969962b8c155eb13157e06cb1c11ab16cedc87e02"
    )
  end

  desc "Build and deploy your (packed) application to beta for testing"
  lane :beta do
    increase_build_number
    pack
    deploy_beta
  end

end
