//
//  LoginInteractor.swift
//  cmeviper
//
//  Created Patipat Sahasapanan on 29/8/2561 BE.
//  Copyright © 2561 CreativeMe. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginInteractor: LoginInteractorInputProtocol {

    weak var presenter: LoginInteractorOutputProtocol?
}
